### ISSUE TITLE
Utilize MD-Drugs

### ISSUE THREAD

**Issue by tichys** [Qbox-project/qbx_drugs#11]
### The problem

qbx_drugs is just qb drugs reskinned and its poopoo doodoo

### Ideal solution

Use MD-Drugs https://github.com/Mustachedom/md-drugs, they rewrote corner selling and all the drugs... works with ox and its open source

**Comment by solareon** [comment]
Have you looked at the code quality of md-drugs? There is mountains and mountains of duplicated code with zero care given to exploitability. He has done good work in terms of adding more drugs but adding 100+ items to the items database instead of using metadata is not the move. Sure it's ox_inventory compatible but it's not built with ox_inventory in mind.

**Comment by solareon** [comment]
@tichys have a look at this code here. Anyone that triggers this netevent anywhere on the server can get these items. no checks on position, etc. This is just one example but it goes on and on within his codebase.

https://github.com/Mustachedom/md-drugs/blob/4af79e979283a064667b5e63848a92ca368cb275/server/lsd.lua#L3-L11

**Comment by MafewTM** [comment]
This is not planned at this time
